# name: Danger actions
# 'on':
#   pull_request:
#     types:
#       [
#         opened,
#         edited,
#         reopened,
#         synchronize,
#         assigned,
#         unassigned,
#         review_requested,
#         review_request_removed,
#       ]
# jobs:
#   danger-ci:
#     name: Danger CI
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@main
#       - uses: actions/setup-node@main
#         with:
#           node-version: 21.x
#         env:
#           RUNNER_TEMP: /tmp
#       - name: yarn install
#         run: yarn install
#       - name: Danger CI
#         uses: vtex/danger@main
#         env:
#           GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
#           REQUIRE_CHANGELOG_VERSION: false
