name: CI/CD

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install dependencies
        run: yarn install
      - name: Ingresar a la carpeta android y ejecutar gradlew
        run: cd android && chmod g+x gradlew gradlew.bat && ./gradlew assembleRelease
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
      - name: Release APK
        uses: softprops/action-gh-release@v1
        with:
          files: android/app/build/outputs/apk/release/app-release.apk
          tag_name: v1.0.${{ github.run_number }} # Ajusta el nombre de la etiqueta
          name: Release v1.0.${{ github.run_number }} # Ajusta el nombre de la Release
          body: Nueva versión de la app disponible.
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Necesario para crear la Release

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: electronsgm@gmail.com
          password: ${{ secrets.GMAIL_APP_PASSWORD }} # Guarda la contraseña en un secreto
          subject: Nueva versión de la app disponible
          body: 'La nueva versión de la app está disponible en la Release: ${{ github.event.repository.html_url }}/releases/tag/v1.0.${{ github.run_number }}  # Enlaza a la Release'
          from: electronsgm@gmail.com
          to: satroniccorp@gmail.com
