name: CI/CD

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install dependencies
        run: yarn install
      - name: Ingresar a la carpeta android y ejecutar gradlew
        run: cd android && chmod g+x gradlew gradlew.bat && ./gradlew assembleRelease
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mailersend.net
          server_port: 587
          username: mlsn.e104ef30f61525ebd99ceef96ccde9d7535716558edd0165c84a054a1df174ce
          password: mlsn.e104ef30f61525ebd99ceef96ccde9d7535716558edd0165c84a054a1df174ce
          #password: 'mlsn.e104ef30f61525ebd99ceef96ccde9d7535716558edd0165c84a054a1df174ce'
          #Zt@vT@HnUCm5wqR
          subject: Nueva versión de la app disponible
          body: 'La nueva versión de la app está disponible para descargar: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/app-release.apk'
          from: electronsgm@gmail.com
          to: satroniccorp@gmail.com
