name: 'coverage'
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  code-quality:
    name: eslint runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm install eslint eslint-config-vtex eslint-config-vtex-react --legacy-peer-deps
      - name: Run ESLint on modified code
        run: npx eslint ./
  # test:
  #   permissions:
  #     pull-requests: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: "14" # Or your specific Node.js version
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Run tests and collect coverage
  #       run: npm test -- --coverage

  #     # Additional step to comment coverage report on PR
  #     - name: Comment PR with coverage report
  #       uses: romeovs/lcov-reporter-action@v0.2.16
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         lcov-file: ./coverage/lcov.info

  # // TODO: Get the emulator working properly and run the tests !
  # automation-tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v3

  #   - name: Set up JDK 11
  #     uses: actions/setup-java@v3
  #     with:
  #       distribution: 'temurin'
  #       java-version: '11'

  #   - name: Set up Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'

  #   - name: Install dependencies
  #     run: |
  #       npm install
  #       npm install -g appium

  #   - name: Set up Android SDK
  #     uses: android-actions/setup-android@v2
  #     with:
  #       api-level: 30
  #       build-tools: 30.0.3
  #       target: android-30
  #       ndk: '23.1.7779620'

  #   - name: Debugging Info
  #     run: |
  #       echo "Android SDK Version:"
  #       $ANDROID_HOME/tools/bin/sdkmanager --version

  #       echo "Available Android Emulators:"
  #       emulator -list-avds

  #       echo "Android Emulator Version:"
  #       $ANDROID_HOME/emulator/emulator -version

  #       echo "ADB Devices:"
  #       adb devices

  #       echo "Appium Version:"
  #       appium -v

  #       echo "Java Version:"
  #       java -version

  #       echo "Node Version:"
  #       node -v

  #       echo "NPM Version:"
  #       npm -v

  #   - name: Start Android emulator
  #     run: |
  #       echo "Starting emulator..."
  #       sudo $ANDROID_HOME/emulator/emulator -avd test -no-snapshot-load -no-audio -no-window &
  #       adb wait-for-device
  #       adb shell input keyevent 82 &

  #   - name: Run Appium Server
  #     run: |
  #       appium --port 4723 &
  #       sleep 10

  #   - name: Run tests
  #     run: |
  #       npm run automationTests
